abstract type Item end
abstract type Resource <: Item end
abstract type Product <: Item end

struct Limestone <: Product end
struct IronOre <: Product end
struct CopperOre <: Product end
struct CateriumOre <: Product end
struct Coal <: Product end
struct RawQuartz <: Product end
struct Sulfur <: Product end
struct Bauxite <: Product end
struct SAMOre <: Product end
struct Uranium <: Product end
struct Water <: Product end
struct CrudeOil <: Product end
struct AlienCarapace <: Product end
struct AlienOrgans <: Product end
struct GreenPowerSlug <: Product end
struct YellowPowerSlug <: Product end
struct PurplePowerSlug <: Product end

struct HeavyOilResidue <: Product end
struct Fuel <: Product end
struct LiquidBiofuel <: Product end
struct Turbofuel <: Product end
struct AluminaSolution <: Product end
struct SulfuricAcid <: Product end
struct Concrete <: Product end
struct IronIngot <: Product end
struct CopperIngot <: Product end
struct CateriumIngot <: Product end
struct SteelIngot <: Product end
struct AluminumIngot <: Product end
struct QuartzCrystal <: Product end
struct PolymerResin <: Product end
struct PetroleumCoke <: Product end
struct AluminumScrap <: Product end
struct Silica <: Product end
struct BlackPowder <: Product end
struct Wire <: Product end
struct Cable <: Product end
struct IronRod <: Product end
struct Screw <: Product end
struct IronPlate <: Product end
struct ReinforcedIronPlate <: Product end
struct CopperSheet <: Product end
struct AlcladAluminumSheet <: Product end
struct Plastic <: Product end
struct Rubber <: Product end
struct PackagedWater <: Product end
struct SteelPipe <: Product end
struct SteelBeam <: Product end
struct EncasedIndustrialBeam <: Product end
# struct GreenPowerSlug <: Product end
# struct YellowPowerSlug <: Product end
# struct PurplePowerSlug <: Product end
struct FlowerPetals <: Product end
struct CrystalOscillator <: Product end
struct EmptyCanister <: Product end
struct Fabric <: Product end
struct ModularFrame <: Product end
struct HeavyModularFrame <: Product end
struct Rotor <: Product end
struct Stator <: Product end
struct Motor <: Product end
struct Quickwire <: Product end
struct CircuitBoard <: Product end
struct Computer <: Product end
struct AILimiter <: Product end
struct HighSpeedConnector <: Product end
struct Supercomputer <: Product end
struct Battery <: Product end
struct HeatSink <: Product end
struct RadioControlUnit <: Product end
struct TurboMotor <: Product end
struct ElectromagneticControlRod <: Product end
struct UraniumPellet <: Product end
struct EncasedUraniumCell <: Product end
struct Beacon <: Product end
struct CompactedCoal <: Product end
struct Leaves <: Product end
struct Mycelia <: Product end
struct Wood <: Product end
struct Biomass <: Product end
struct PackagedOil <: Product end
struct PackagedHeavyOilResidue <: Product end
struct SolidBiofuel <: Product end
struct PackagedFuel <: Product end
struct PackagedLiquidBiofuel <: Product end
struct PackagedTurbofuel <: Product end
struct NuclearFuelRod <: Product end
struct Nobelisk <: Product end
struct GasFilter <: Product end
struct ColorCartridge <: Product end
struct RifleCartridge <: Product end
struct SpikedRebar <: Product end
struct IodineInfusedFilter <: Product end
struct PowerShard <: Product end
struct FICSITCoupon <: Product end
struct SmartPlating <: Product end
struct VersatileFramework <: Product end
struct AutomatedWiring <: Product end
struct ModularEngine <: Product end
struct AdaptiveControlUnit <: Product end