abstract type Product end

for s in (:AILimiter, :AdaptiveControlUnit, :AlcladAluminumSheet, :AlienCarapace, :AlienOrgans, :AluminaSolution, :AluminumCasing, :AluminumIngot, :AluminumScrap, :AssemblyDirectorSystem, :AutomatedWiring, :Battery, :Bauxite, :Beacon, :Biomass, :BlackPowder, :Cable, :CateriumIngot, :CateriumOre, :CircuitBoard, :Coal, :ColorCartridge, :CompactedCoal, :Computer, :Concrete, :CoolingSystem, :CopperIngot, :CopperOre, :CopperPowder, :CopperSheet, :CrudeOil, :CrystalOscillator, :ElectromagneticControlRod, :EmptyCanister, :EmptyFluidTank, :EncasedIndustrialBeam, :EncasedPlutoniumCell, :EncasedUraniumCell, :FICSITCoupon, :Fabric, :FlowerPetals, :Fuel, :FusedModularFrame, :GasFilter, :GreenPowerSlug, :HeatSink, :HeavyModularFrame, :HeavyOilResidue, :HighSpeedConnector, :IodineInfusedFilter, :IronIngot, :IronOre, :IronPlate, :IronRod, :Leaves, :Limestone, :LiquidBiofuel, :MagneticFieldGenerator, :ModularEngine, :ModularFrame, :Motor, :Mycelia, :NitricAcid, :NitrogenGas, :Nobelisk, :NonfissileUranium, :NuclearPasta, :PackagedAluminaSolution, :PackagedFuel, :PackagedHeavyOilResidue, :PackagedLiquidBiofuel, :PackagedNitricAcid, :PackagedNitrogenGas, :PackagedOil, :PackagedSulfuricAcid, :PackagedTurbofuel, :PackagedWater, :PetroleumCoke, :Plastic, :PlutoniumFuelRod, :PlutoniumPellet, :PlutoniumPellets, :PolymerResin, :PortableMiner, :PowerShard, :PressureConversionCube, :PurplePowerSlug, :QuartzCrystal, :Quickwire, :RadioControlUnit, :RawQuartz, :ReinforcedIronPlate, :RifleCartridge, :Rotor, :Rubber, :SAMOre, :Screw, :Silica, :SmartPlating, :SolidBiofuel, :SpikedRebar, :Stator, :SteelBeam, :SteelIngot, :SteelPipe, :Sulfur, :SulfuricAcid, :Supercomputer, :ThermalPropulsionRocket, :TurboMotor, :Turbofuel, :Uranium, :UraniumFuelRod, :UraniumPellet, :UraniumWaste, :VersatileFramework, :Water, :Wire, :Wood, :YellowPowerSlug)
    @eval struct $s <: Product end
    @eval export $s
end

struct ErrorProductNotFound <: Product
end
export ErrorProductNotFound